spring.application.name=AI-Revenue-Recovery
spring.datasource.url=jdbc:mysql://localhost:3306/revenue_recovery_db
spring.datasource.username=root
spring.datasource.password=Yashit@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Razorpay Configuration
razorpay.key.id=YOUR_RAZORPAY_KEY_ID
razorpay.key.secret=YOUR_RAZORPAY_KEY_SECRET

# Spring AI Google GenAI
spring.ai.google.genai.api-key=YOUR_GEMINI_API_KEY

# Task Scheduling
spring.task.scheduling.pool.size=2
